### ISSUE TITLE
具体怎么用？

### ISSUE THREAD

**Issue by ddiiccoo** [zhxie/pcap2socks#14]
请问这个东西具体怎么用？不大会用，比起TUN2SOCKS难多了。跑起来后，这个10.6.0.1是干嘛用的？有比较详细的使用教程么？

**Comment by zhxie** [comment]
pcap2socks is a proxy used to redirect other devices' traffic in the local area network, such as Nintendo Switch & PlayStation, and does not support proxy local traffic.

pcap2socks uses a tech called pcap to capture network packets, bypass the kernal's protocol stack, and redirect network traffic.

To bypass the kernel's protocol stack, especially in macOS & Linux, the Proxy ARP should be enabled by setting `--publish <ADDRESS>`, and all the traffic from `SRC_ADDRESS` to `PUBLISH_ADDRESS` will be captued by pcap2socks.

After starting pcap2socks correctly, a prompt message will appear on the screen, like
```
┌───────────────────────────┐
│ IP Address       10.6.0.1 │
│ Mask        255.255.255.0 │
│ Gateway          10.6.0.2 │
│───────────────────────────│
│ MTU                <=1500 │
└───────────────────────────┘
```
and you have to fill these parameters to your proxied device's network settings. You can also choose [pcap2socks GUI](https://github.com/zhxie/pcap2socks-gui) with user interface.

---

pcap2socks 是用于重定向局域网中其他设备，如 Nintendo Switch 与 PlayStation，的流量的代理，不能用于代理本地流量。

pcap2socks 使用了被称为 pcap 的技术来捕获网络报文，绕过内核的协议栈，并重定向网络流量。

为了绕过内核的协议栈，尤其是在 macOS 与 Linux 中，需要通过 `--publish <ADDRESS>` 启用 Proxy ARP，这样，所有来自 `SRC_ADDRESS` 到 `PUBLISH_ADDRESS` 的流量都将被 pcap2socks 所捕获。

在正确启动 pcap2socks 后，屏幕上将显示如下
```
┌───────────────────────────┐
│ IP Address       10.6.0.1 │
│ Mask        255.255.255.0 │
│ Gateway          10.6.0.2 │
│───────────────────────────│
│ MTU                <=1500 │
└───────────────────────────┘
```
的提示信息，你仅需将这些信息填写到被代理的设备的网络设置中即可。你也可以选择使用具有交互式界面的 [pcap2socks GUI](https://github.com/zhxie/pcap2socks-gui).
