### ISSUE TITLE
How to use the application

### ISSUE THREAD

**Issue by fsheidaiee** [zhxie/pcap2socks#16]
Hi
I have xray core on socks5 port 10808
how I can use the app?
I didnt understand from the usage part of your docs.
thanks

**Comment by zhxie** [comment]
You may launch pcap2socks with
```
pcap2socks -s 10.10.0.2 -p 10.10.0.1 -d localhost:10808
```
and configure your proxied device's network settings by following the prompt message displayed in the screen like
```
┌───────────────────────────┐
│ IP Address      10.10.0.2 │
│ Mask        255.255.255.0 │
│ Gateway         10.10.0.1 │
│───────────────────────────│
│ MTU                <=1500 │
└───────────────────────────┘
```

In addition, pcap2socks is a proxy used to redirect other devices' traffic in the local area network, such as Nintendo Switch & PlayStation, and does not support proxy local traffic.
