### ISSUE TITLE
在ps4上设置完无法加速并提示错误代码

### ISSUE THREAD

**Issue by WisdomDevils** [zhxie/pcap2socks#19]
提示为warning: receive from proxy: TCP: 23.49.1.147:443 -> 0: 你的主机中的软件中止了一个已建立的连接。 (os error 10053)

**Comment by zhxie** [comment]
What's your OS and launch arguments?

**Comment by WisdomDevils** [comment]
win10使用npcap

**Comment by WisdomDevils** [comment]
在ps4连接浏览器时也会出现thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code', C:\Users\Xie\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\src\libstd\macros.rs:13:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
这有问题吗？

**Comment by zhxie** [comment]
Launch arguments and pcap2socks version?

**Comment by WisdomDevils** [comment]
我用最新发布的pcap2socks
在netch上使用

**Comment by zhxie** [comment]
I am not familiar with how Netch launches pcap2socks. If possible, please launch pcap2socks independently, with argument `-vv` attached for debug and verbose information and `-V` for version of pcap2socks. In addition, pcap2socks requires admin access and privileges. 

If you meet with the same problem again, please comment and attach the output information. I can not do any investigation without sufficient information.

**Comment by WisdomDevils** [comment]
好的 谢谢
