### ISSUE TITLE
可提供mac版的可执行文件下载吗

### ISSUE THREAD

**Issue by briteming** [zhxie/pcap2socks#2]
我在mac上，build失败。即使是挂着vpn进行build,仍然失败：
yudeMacBook-Air:pcap2socks-by-zhxie brite$ cargo build --release
    Updating crates.io index

warning: spurious network error (2 tries remaining): failed to connect to github.com: Operation timed out; class=Os (2)
warning: spurious network error (1 tries remaining): failed to connect to github.com: Operation timed out; class=Os (2)
error: failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to connect to github.com: Operation timed out; class=Os (2)

**Comment by zhxie** [comment]
You can get the CI automatically compiled executable file in [Actions](https://github.com/zhxie/pcap2socks/actions).

---

你可以在 [Actions](https://github.com/zhxie/pcap2socks/actions) 中获得 CI 自动编译的版本。

**Comment by briteming** [comment]
下载了。不过，
./pcap2socks --source <ADDRESS> --destination 127.0.0.1:1080 --interface tun10

“--source”的值该怎么写？

**Comment by zhxie** [comment]
Please refer to the [Usage](https://github.com/zhxie/pcap2socks#usage)

---

请参考 [Usage](https://github.com/zhxie/pcap2socks#usage)

```
// Example: proxy 10.6.0.1 to 127.0.0.1:1080 with proxy ARP 10.6.0.2
pcap2socks -s 10.6.0.1 -p 10.6.0.2 -d 127.0.0.1:1080
```

**Comment by briteming** [comment]
./pcap2socks --source 10.6.0.2 --publish 10.6.0.1 --destination 127.0.0.1:1080 --interface en0
显示：
Listen on en0 [e0:ac:cb:76:bc:a6]: 192.168.1.100
Break packets with MTU 1400
Publish for 10.6.0.1
Please set the network of your device which is going to be proxied with the following parameters:
    ┌────────────────────────────┐
    │ IP Address        10.6.0.2 │
    │ Mask         255.255.255.0 │
    │ Gateway           10.6.0.1 │
    │────────────────────────────│
    │ MTU                   1400 │
    └────────────────────────────┘
error: No such file or directory (os error 2)
yudeMacBook-Air:pcap2socks-latest-macOS-amd64 brite$

怎么解决？

**Comment by zhxie** [comment]
Please refer to the [Troubleshoot](https://github.com/zhxie/pcap2socks#troubleshoot), and confirm if you have the root access.

---

请参考 [Troubleshoot](https://github.com/zhxie/pcap2socks#troubleshoot)，并确认是否拥有 root 权限。

**Comment by briteming** [comment]
hi.
我运行了：
sudo sysctl -w net.inet.ip.forwarding=0
然后运行：
sudo ./pcap2socks --source 10.6.0.2 --publish 10.6.0.1 --destination 127.0.0.1:1080 --interface en0
显示：
Listen on en0 [e0:ac:cb:76:bc:a6]: 192.168.1.101
Break packets with MTU 1400
Publish for 10.6.0.1
Please set the network of your device which is going to be proxied with the following parameters:
    ┌────────────────────────────┐
    │ IP Address        10.6.0.2 │
    │ Mask         255.255.255.0 │
    │ Gateway           10.6.0.1 │
    │────────────────────────────│
    │ MTU                   1400 │
    └────────────────────────────┘
Proxy 10.6.0.2 to 127.0.0.1:1080

然后，我在浏览器里，访问显示IP的网站，显示的ip仍然是我的ISP分配给我的ip,并非我的服务器的ip.也翻不了墙。

你这个可执行文件pcap2socks是不是缺乏设置本机的 IP Address , Mask和 Gateway的ip地址的参数？

**Comment by zhxie** [comment]
pcap2socks is used to proxy other devices in your LAN. It was originally designed as a game accelerator and cannot be used to proxy the local machine.

---

pcap2socks 是用于代理局域网中其它设备的，其设计初衷是一个游戏加速器，并不能用于代理本机。

**Comment by briteming** [comment]
能基于你这个项目，另外搞个全局代理的项目吗？

**Comment by zhxie** [comment]
If you are interested, you can fork this project or use it arbitrarily in compliance with [the MIT license](https://github.com/zhxie/pcap2socks/blob/master/LICENSE). But I will not add this feature to it.

---

如果你有兴趣，你可以 fork 这个项目，或是在遵守 [MIT 协议](https://github.com/zhxie/pcap2socks/blob/master/LICENSE)的情况下任意使用这个项目。但我不会为其增加该功能。
