### ISSUE TITLE
MacOS版本能用于uBuntu吗

### ISSUE THREAD

**Issue by knudalr** [zhxie/pcap2socks#20]
使用windows版本已经实现对V2Ray链接的成功转发。

想在Linux（无Gui）下也实现，我感觉SSR和V2Ray的Linux CLI Client好找，但我不知道你的MacOS版本能否用于Ubuntu，当然Centos等都行。

请看看。

如果不行，能否出个Linux版本，谢谢

**Comment by zhxie** [comment]
You can just build it in your preferred OS.

**Comment by knudalr** [comment]
没有使用过Rust，不清楚如何用toml构建：（
能否请您帮忙build一个ubuntu的包，非常感谢

**Comment by zhxie** [comment]
Anyway, you can use the [binary](https://github.com/zhxie/pcap2socks/actions) built by the CI.
