### ISSUE TITLE
Cannot compile in Raspberry(arm64)

### ISSUE THREAD

**Issue by lams2135** [zhxie/pcap2socks#23]
cannot compile in Raspberry.
Looks like a dependency issue, but are there anything instead available?

   Compiling socket2 v0.4.1
error: attributes are not yet allowed on `if` expressions
   --> /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.1/src/sys/unix.rs:878:5
    |
878 |     #[cfg(not(any(target_os = "haiku", target_os = "openbsd")))]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by lams2135** [comment]
I updated rustc to resolve this issue.

**Comment by sddpljx** [comment]
Sorry to bother you! I tried to compile in my Raspberry r2s, but I still have some errors. Cloud you please send me an compiled file？
Looking forward to your reply!

**Comment by lams2135** [comment]
> Sorry to bother you! I tried to compile in my Raspberry r2s, but I still have some errors. Cloud you please send me an compiled file？ Looking forward to your reply!

You can check the version of your rustc and update or re-install from official website / snap . I guess you had installed rustc directly from apt-get which provides an old version. The latest version of rustc can resolve that issue.
