### ISSUE TITLE
macos运行的时候提示warning，CommandNotSupported

### ISSUE THREAD

**Issue by pigKinger** [zhxie/pcap2socks#24]
![image](https://user-images.githubusercontent.com/50476515/152777471-44aec0a7-2ecd-4ecc-928e-afdd62b20369.png)
warning: handle UDP: 192.168.31.36:45945 -> 8.8.8.8:53, Length = 48: Unsuccessful reply: CommandNotSupported

是需要安装什么依赖工具吗？

**Comment by zhxie** [comment]
Are your `-s` and `-p` parameters the same as the subnet your Mac is on?

---

你的`-s`与`-p`参数与你Mac所在的子网相同吗？
