### ISSUE TITLE
switch DNS解析失败

### ISSUE THREAD

**Issue by gitthehit** [zhxie/pcap2socks#27]
我在本地同时启用了clash和pcap2socks，其中clash连接国内vps上的shadowsocks，pcapsocks也可以正常代理switch，但是点击“连接到此网络”的时候，总是会跳DNS解析失败。如果我在服务器上直接建立socks5 server，可以获得NAT A，但是测速结果感人，基本上只有几十kbps。想知道第一种方式为什么连接不上。

后来测试发现，第一种方法，如果我指定dns为路由器地址，就可以正常代理，但是nat只有F，很奇怪。

**Comment by mudebug77** [comment]
这个代理工具会代理udp协议，但是如果你假设的socket5不支持udp协议，就会无法联网了，因为dns是udp协议，他无法查询到IP
