### ISSUE TITLE
跳出错误

### ISSUE THREAD

**Issue by kszym2002** [zhxie/pcap2socks#3]
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

变量加入RUST_BACKTRACE=1

跳出
  left: `65501`,
 right: `1480`: destination and source slices have different lengths', /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libcore\macros\mod.rs:18:13
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: BaseThreadInitThunk
  22: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

变量 RUST_BACKTRACE=full
  left: `65501`,
 right: `1480`: destination and source slices have different lengths', /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libcore\macros\mod.rs:18:13
stack backtrace:
   0:     0x7ff63b85943f - <unknown>
   1:     0x7ff63b86bd4b - <unknown>
   2:     0x7ff63b851bec - <unknown>
   3:     0x7ff63b85c74c - <unknown>
   4:     0x7ff63b85c39f - <unknown>
   5:     0x7ff63b85cf27 - <unknown>
   6:     0x7ff63b85caaf - <unknown>
   7:     0x7ff63b86b050 - <unknown>
   8:     0x7ff63b6f6a7d - <unknown>
   9:     0x7ff63b6f7684 - <unknown>
  10:     0x7ff63b6da0da - <unknown>
  11:     0x7ff63b6e7d76 - <unknown>
  12:     0x7ff63b6ef1cc - <unknown>
  13:     0x7ff63b6e7f90 - <unknown>
  14:     0x7ff63b6ba19f - <unknown>
  15:     0x7ff63b6ecb86 - <unknown>
  16:     0x7ff63b85c947 - <unknown>
  17:     0x7ff63b8611f2 - <unknown>
  18:     0x7ff63b85d168 - <unknown>
  19:     0x7ff63b6ba337 - <unknown>
  20:     0x7ff63b872c94 - <unknown>
  21:     0x7ffa64c67bd4 - BaseThreadInitThunk
  22:     0x7ffa650cce51 - RtlUserThreadStart

**Comment by zhxie** [comment]
Is the stack backtrace like this? Because most of it is empty, it is not possible to determine the problem.

---

Stack backtrace 就是这样的吗？因为大部分都是空的，所以并不能确定问题所在。

**Comment by zhxie** [comment]
If you use the binary files in releases or actions directly, they may not have debugging symbols inserted during compilation. If possible, hope to clone the code and compile and run under debug.

---

如果你直接使用了 releases 或者 actions 中的二进制文件，它们在编译时可能没有置入调试符号。如果可以的话，希望能 clone 代码并在 debug 下编译运行。

**Comment by zhxie** [comment]
Although there is no backtrace, I guess the problem is in [here](https://github.com/zhxie/pcap2socks/blob/master/src/packet/mod.rs#L409), I will try to fix it. And you can download the newly compiled file in actions after the next push.

---

虽然没有 backtrace，但我盲猜在[这儿](https://github.com/zhxie/pcap2socks/blob/master/src/packet/mod.rs#L409)，下次 push 的时候我会尝试修复，届时你可以去 actions 中下载新编译完毕的文件。
