### ISSUE TITLE
请问下主机的DNS如何填写？

### ISSUE THREAD

**Issue by Rakau** [zhxie/pcap2socks#30]
我想让服务端来解析DNS，而不是主机来解析DNS。主机可以填常规的公共DNS可以连接。但是如果填了服务端的网关就提示出错。主机是Switch

**Comment by zhxie** [comment]
pcap2socks does not own a local DNS server. You should designate a existed public DNS server in your console.

**Comment by Rakau** [comment]
> pcap2socks does not own a local DNS server. You should designate a existed public DNS server in your console.

请问如何操作呢，文档没看到有关于DNS的用法

**Comment by zhxie** [comment]
You can just use any public DNS in your console.
