### ISSUE TITLE
大佬怎么联系你？

### ISSUE THREAD

**Issue by menglinxi** [zhxie/pcap2socks#37]
大佬怎么联系你？v 345728984

**Comment by zhxie** [comment]
This project is outdated, please refer to applications built through virtual network devices such as TUN/TAP and network stacks subch as smoltcp and gVisor Networking when possible. If you need any help, please contact me via mail.

---

这个项目已经过时了，请尽可能参考通过TUN/TAP等虚拟网络设备以及smoltcp、gVisor Networking等协议栈构建的应用。如需任何帮助，请通过电子邮件联系我。

**Comment by menglinxi** [comment]
大佬，有没有最新的适合做游戏加速器的开源项目介绍？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月4日(星期天) 下午5:27
收件人: ***@***.***&gt;; 
抄送: "广州天势 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhxie/pcap2socks] 大佬怎么联系你？ (Issue #37)





 
This project is outdated, please refer to applications built through virtual network devices such as TUN/TAP and network stacks subch as smoltcp and gVisor Networking when possible. If you need any help, please contact me via mail.
 
 
这个项目已经过时了，请尽可能参考通过TUN/TAP等虚拟网络设备以及smoltcp、gVisor Networking等协议栈构建的应用。如需任何帮助，请通过电子邮件联系我。

**Comment by zhxie** [comment]
相比起技术，对于游戏加速器而言还是线路比较重要。但是因为很难找到便宜、稳定而又低延迟的线路，所以我已经直接选择购买服务商提供的加速器了。如果你想要自己构建，那可以参考[switch-lan-play](https://github.com/spacemeowx2/switch-lan-play)、[tun2proxy](https://github.com/blechschmidt/tun2proxy)以及[Netch](https://github.com/netchx/netch)。事实上，你只需要3步，通过ARP欺骗捕获流量，处理协议栈，代理流量。

**Comment by menglinxi** [comment]
v2ray,客户端+优质节点，能搞定？
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月4日(星期天) 下午5:37
收件人: ***@***.***&gt;; 
抄送: "广州天势 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhxie/pcap2socks] 大佬怎么联系你？ (Issue #37)





 
相比起技术，对于游戏加速器而言还是线路比较重要。但是因为很难找到便宜、稳定而又低延迟的线路，所以我已经直接选择购买服务商提供的加速器了。如果你想要自己构建，那可以参考switch-lan-play、tun2proxy以及Netch。事实上，你只需要3步，通过ARP欺骗捕获流量，处理协议栈，代理流量。

**Comment by zhxie** [comment]
我不了解V2Ray。

**Comment by DaniilSokolyuk** [comment]
I'm looking for an alternative that works on L2 (tap driver) and implements an arp server so that you can connect a console or a printer, for example. a lot of implementation with tun (l3) and gvisor but this is not the same

**Comment by zhxie** [comment]
Actually, I barely see easy-to-use cross-platform implementation. Apps like pcap2socks usually built on Windows only. (Since only geeks using Linux and they certainly known tools like iptables.) I hope someone may create similar app using TAP, ARP spoofing and open source network stacks.

**Comment by DaniilSokolyuk** [comment]
i tried to use tap from
https://github.com/songgao/water
but i didnt get arp requests from devices, perhaps there is a problem in the driver configuration in water or some kind of manipulation with the network bridge is required, idk

**Comment by DaniilSokolyuk** [comment]
i ported it to golang https://github.com/DaniilSokolyuk/go-pcap2socks based on tun2socks implementation with gvisor stack

**Comment by zagfai** [comment]
@zhxie 你的工作还是有价值的，在没有iptables的机器上
