### ISSUE TITLE
使用一段时间会无网络

### ISSUE THREAD

**Issue by kckm** [zhxie/pcap2socks#8]
使用手机浏览器播放视频，几个app刷一刷，大概不到半小时，把后台清空，再打开浏览器就连接不上网络了。重启pcap2socks能恢复正常。
[log.zip](https://github.com/zhxie/pcap2socks/files/5464799/log.zip)

**Comment by kckm** [comment]
我又试了下，打开一些网页和app，之后清空后台，重复若干次就会出现这个问题。

**Comment by zhxie** [comment]
应该是 UDP 绑定的记录表出现了问题，但是这个日志实在是太多了，得看一段时间，如果有 Wireshark 之类的软件的抓包记录的话会更好。

**Comment by zhxie** [comment]
感谢反馈，这一问题似乎是由 842be88 中一处疏忽引起的 UDP 绑定失效带来的。

烦请测试一下[这一 build](https://github.com/zhxie/pcap2socks/files/5465685/pcap2socks-v0.6.0_284r1-windows-amd64.zip) 是否解决了这一问题，谢谢。

**Comment by kckm** [comment]
测试了20分钟，目前一切正常，应该是已经解决这个问题了。
